### PR TITLE
fix combo sync

### PR DESCRIPTION
**Pull request by yochan0412**
delete url GET Method param

### CODE REVIEW

**Review by z891107 — CHANGES_REQUESTED** [review]
Please rollback const value for DIFFICULTIES_INFO

**Comment by yochan0412** [comment]
rollback const value of DIFFICULTIES_INFO

**Comment by yochan0412** [comment]
ARE YOU READY?

**Review by z891107 — APPROVED** [review]

**Comment by z891107** [comment]
something yochan fixed

**Pull request merged**
